import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'pl' | 'en';

interface LanguageContextType {
    lang: Language;
    toggleLang: () => void;
    t: (path: string) => string;
}

const translations = {
    pl: {
        nav: {
            home: 'Strona główna',
            services: 'Usługi',
            team: 'Zespół',
            reviews: 'Opinie',
            bookAppointment: 'Zarezerwuj wizytę',
            account: 'Konto',
            profile: 'Profil',
            dashboard: 'Panel',
            logout: 'Wyloguj',
            login: 'Zaloguj się',
            register: 'Zarejestruj się',
        },
        adminMenu: {
            overview: 'Przegląd',
            users: 'Użytkownicy',
            appointments: 'Wizyty',
            services: 'Usługi',
            reviews: 'Opinie',
        },
        home: {
            heroTitle: 'Klasyczne cięcia',
            heroSubtitle: 'w nowoczesnym stylu',
            heroDescription: 'Premium usługi barberskie dla wymagających mężczyzn. Doświadcz perfekcyjnej pielęgnacji w swobodnej, ale profesjonalnej atmosferze.',
            bookNow: 'Zarezerwuj wizytę',
            ourServices: 'Nasze usługi',
            whyChooseUs: 'Dlaczego warto wybrać nasz barbershop?',
            whySubtitle: 'Łączymy klasyczne rzemiosło barberskie z nowoczesnym stylem, oferując usługi na najwyższym poziomie wykonywane przez doświadczony zespół.',
            feature1Title: 'Doświadczeni barberzy',
            feature1Desc: 'Nasz zespół tworzą wykwalifikowani specjaliści z wieloletnim doświadczeniem w nowoczesnych i klasycznych technikach strzyżenia.',
            feature2Title: 'Wygodna rezerwacja',
            feature2Desc: 'Nasz system rezerwacji online pozwala łatwo zaplanować wizytę w dogodnym dla Ciebie terminie, o każdej porze – 24/7.',
            feature3Title: 'Usługi premium',
            feature3Desc: 'Od klasycznego strzyżenia, przez modelowanie brody, po gorące ręczniki – oferujemy szeroki zakres usług dopasowanych do Twoich potrzeb.',
            feature4Title: 'Wysokiej jakości produkty',
            feature4Desc: 'Korzystamy wyłącznie ze sprawdzonych kosmetyków do włosów i brody, aby zapewnić najlepszy efekt i długotrwały rezultat.',
            ctaTitle: 'Gotowy na nowy, świeży wygląd?',
            ctaDescription: 'Zarezerwuj wizytę już dziś i skorzystaj z naszych usług premium. Dobrze wyglądać jeszcze nigdy nie było tak prosto.',
            ctaButton: 'Zarezerwuj teraz',
            ctaImageAlt: 'Wnętrze barber shopu',
        },
        footer: {
            tagline: 'Usługi premium dla mężczyzny. Doświadcz tradycji barberskiej w nowoczesnym wydaniu.',
            quickLinks: 'Szybkie linki',
            team: 'Nasz zespół',
            servicesTitle: 'Usługi',
            haircut: 'Strzyżenie',
            beardTrim: 'Trymowanie brody',
            hotTowelShave: 'Golenie z gorącym ręcznikiem',
            hairColoring: 'Koloryzacja włosów',
            kidsHaircut: 'Strzyżenie dziecięce',
            contact: 'Kontakt',
            allRightsReserved: 'Wszelkie prawa zastrzeżone.',
            privacyPolicy: 'Polityka prywatności',
            terms: 'Regulamin',
            contactUs: 'Skontaktuj się z nami',
        },
        dashboard: {
            welcome: 'Witaj',
            overview: 'Przegląd',
            appointments: 'Wizyty',
            profile: 'Profil',
            reviews: 'Opinie',
            notifications: 'Powiadomienia',
            schedule: 'Grafik',
            portfolio: 'Portfolio',
            users: 'Użytkownicy',
            services: 'Usługi',
            reports: 'Raporty',
            logout: 'Wyloguj',
            adminPanel: 'Panel Administratora',
            barberPanel: 'Panel Barbera',
            clientPanel: 'Panel Klienta',
        },
        services: {
            title: 'Nasze usługi',
            subtitle: 'Od klasycznych cięć po zabiegi pielęgnacyjne premium – oferujemy szeroki zakres usług dopasowanych do nowoczesnego mężczyzny.',
            bookAppointment: 'Zarezerwuj wizytę',
            loading: 'Ładowanie listy usług...',
            noServices: 'Obecnie brak dostępnych usług.',
            noServicesHint: 'Sprawdź ponownie w późniejszym terminie.',
            duration: 'min',
        },
        team: {
            title: 'Nasz zespół',
            heroTitle: 'Poznaj nasz zespół',
            subtitle: 'Poznaj naszych wykwalifikowanych specjalistów, którzy zadbają o Twój wygląd.',
            heroSubtitle: 'Nasi barberzy i styliści łączą wieloletnie doświadczenie z pasją, dbając o każdy szczegół Twojej wizyty.',
            experience: 'lat doświadczenia',
            bookWith: 'Zarezerwuj z',
            seePortfolio: 'Zobacz portfolio',
            allSpecializations: 'Wszyscy',
            searchPlaceholder: 'Szukaj po imieniu lub roli...',
            viewProfile: 'Zobacz profil',
            loading: 'Ładowanie członków zespołu...',
            noMembers: 'Brak członków zespołu spełniających wybrane kryteria.',
            noMembersHint: 'Spróbuj zmienić wyszukiwanie lub filtry.',
            specializations: 'Specjalizacje',
            certifications: 'Certyfikaty',
            contact: 'Kontakt',
            portfolioTitle: 'Portfolio',
            about: 'O',
            noDescription: 'Brak dodanego opisu.',
            bookWithPerson: 'Umów wizytę z',
            photoOf: 'Zdjęcie',
            of: 'z',
            noPhotos: 'Brak zdjęć do wyświetlenia.',
            notFound: 'Nie udało się wczytać szczegółów barbera lub barber nie został znaleziony.',
        },
        reviews: {
            title: 'Opinie klientów',
            subtitle: 'Zobacz, co nasi klienci mówią o swoich wizytach w naszym barbershopie.',
            ratingSummary: 'Podsumowanie ocen',
            totalReviews: 'łącznie opinii',
            reviewCount: 'opinii',
            searchPlaceholder: 'Szukaj w opiniach...',
            filterAll: 'Wszystkie oceny',
            sortNewest: 'Najnowsze',
            sortHighest: 'Najwyżej ocenione',
            sortLowest: 'Najniżej ocenione',
            loading: 'Ładowanie opinii...',
            helpful: 'Pomocna',
            unhelpful: 'Nieprzydatna',
            noReviews: 'Nie znaleziono opinii spełniających wybrane kryteria.',
            clearFilters: 'Wyczyść filtry',
            beFirst: 'Bądź pierwszą osobą, która oceni nasze usługi!',
            barberLabel: 'barber',
            starSingular: 'gwiazdka',
            starFew: 'gwiazdki',
            starMany: 'gwiazdek',
            invalidDate: 'Nieprawidłowa data',
        },
        booking: {
            title: 'Zarezerwuj wizytę',
            subtitle: 'Wybierz usługę, barbera i termin który Ci odpowiada.',
        },
        auth: {
            loginTitle: 'Zaloguj się',
            loginWelcome: 'Witaj ponownie',
            loginSubtitle: 'Wpisz swoje dane aby uzyskać dostęp do konta.',
            loginSubtitleFull: 'Wprowadź adres e‑mail i hasło, aby zalogować się na swoje konto',
            registerTitle: 'Utwórz konto',
            registerSubtitle: 'Zarejestruj się, aby móc rezerwować wizyty.',
            registerSubtitleFull: 'Wprowadź swoje dane, aby utworzyć nowe konto',
            email: 'Adres e-mail',
            password: 'Hasło',
            firstName: 'Imię',
            lastName: 'Nazwisko',
            phone: 'Numer telefonu',
            loginButton: 'Zaloguj się',
            registerButton: 'Zarejestruj się',
            noAccount: 'Nie masz konta?',
            hasAccount: 'Masz już konto?',
            signUpLink: 'Zarejestruj się',
            signInLink: 'Zaloguj się',
            forgotPassword: 'Zapomniałeś hasła?',
            loggingIn: 'Logowanie...',
            creatingAccount: 'Tworzenie konta...',
            confirmPassword: 'Potwierdź hasło',
            or: 'Lub',
            emailRequired: 'Adres e‑mail jest wymagany',
            emailInvalid: 'Adres e‑mail jest nieprawidłowy',
            passwordRequired: 'Hasło jest wymagane',
            passwordMin: 'Hasło musi mieć co najmniej 6 znaków',
            firstNameRequired: 'Imię jest wymagane',
            lastNameRequired: 'Nazwisko jest wymagane',
            phoneRequired: 'Numer telefonu jest wymagany',
            passwordsMismatch: 'Hasła nie są zgodne',
            loginFailed: 'Logowanie nie powiodło się. Sprawdź dane i spróbuj ponownie.',
            registerFailed: 'Rejestracja nie powiodła się. Spróbuj ponownie.',
        },
        common: {
            loading: 'Ładowanie...',
            save: 'Zapisz',
            cancel: 'Anuluj',
            edit: 'Edytuj',
            delete: 'Usuń',
            confirm: 'Potwierdź',
            back: 'Wstecz',
            close: 'Zamknij',
            noValue: 'Brak',
            actions: 'Akcje',
            goToLogin: 'Przejdź do logowania',
            invalidDate: 'Nieprawidłowa data',
            saveChanges: 'Zapisz zmiany',
            all: 'Wszystkie',
            search: 'Szukaj...',
            add: 'Dodaj',
            name: 'Nazwa',
            description: 'Opis',
            price: 'Cena',
            date: 'Data',
            status: 'Status',
            show: 'Pokaż',
        },
        adminPanel: {
            title: 'Panel Administratora',
            loading: 'Ładowanie...',
            authError: 'Błąd autoryzacji. Proszę się zalogować.',
            overview: {
                visitsByCount: 'Wizyty (liczba)',
                revenue: 'Przychód (PLN)',
                users: 'Użytkownicy',
                activeAppointments: 'Aktywne Wizyty',
                allServices: 'Wszystkie usługi',
                monthlyRevenue: 'Miesięczny przychód',
                todayCompleted: 'Zakończone wizyty dzisiaj',
                todayChartDesc: 'Godzinowe zestawienie liczby zakończonych wizyt i przychodów.',
                hour: 'Godzina',
                appointmentCount: 'Liczba wizyt',
                revenueLabel: 'Przychód (PLN)',
                noDataToday: 'Na dziś nie odnotowano jeszcze żadnych zakończonych wizyt ani przychodów.',
                notifications: 'Powiadomienia',
                latestNotifications: 'Ostatnie najważniejsze powiadomienia.',
                noNewNotifications: 'Brak nowych powiadomień',
                errorStats: 'Nie udało się wczytać statystyk ogólnych.',
                errorActivity: 'Nie udało się wczytać dzisiejszej aktywności.',
                errorNotifications: 'Nie udało się wczytać powiadomień.',
                errorDashboard: 'Nie udało się wczytać danych panelu.',
            },
            users: {
                title: 'Zarządzanie użytkownikami',
                subtitle: 'Przeglądaj, edytuj i zarządzaj wszystkimi użytkownikami w systemie.',
                filterByRole: 'Filtruj według roli',
                allRoles: 'Wszystkie role',
                clients: 'Klienci',
                barbersLabel: 'Barberzy',
                admins: 'Administratorzy',
                colName: 'Imię i nazwisko',
                colEmail: 'Email',
                colPhone: 'Telefon',
                colRole: 'Rola',
                colCreated: 'Utworzono',
                colActions: 'Akcje',
                noValue: 'Brak',
                roleAdmin: 'Administrator',
                roleBarber: 'Barber',
                roleClient: 'Klient',
                editUser: 'Edytuj użytkownika',
                editUserDesc: 'Zaktualizuj dane użytkownika oraz jego rolę.',
                firstName: 'Imię',
                lastName: 'Nazwisko',
                roleLabel: 'Rola',
                cancel: 'Anuluj',
                saveChanges: 'Zapisz zmiany',
                deleteUser: 'Usuń użytkownika',
                deleteUserConfirm: 'Czy na pewno chcesz usunąć tego użytkownika? Tej akcji nie można cofnąć.',
                delete: 'Usuń',
                updated: 'Użytkownik został zaktualizowany.',
                deleted: 'Użytkownik został usunięty.',
                firstNameMin: 'Imię musi mieć co najmniej 2 znaki.',
                lastNameMin: 'Nazwisko musi mieć co najmniej 2 znaki.',
                invalidEmail: 'Nieprawidłowy adres e-mail.',
                updateFailed: 'Aktualizacja nie powiodła się.',
                deleteFailed: 'Nie udało się usunąć użytkownika.',
                loadFailed: 'Nie udało się wczytać listy użytkowników.',
                phoneLabel: 'Telefon: ',
                createdLabel: 'Utworzono: ',
                fullNameLabel: 'Imię i nazwisko: ',
            },
            appointments: {
                title: 'Zarządzanie wizytami',
                clearFilters: 'Wyczyść filtry',
                filterByStatus: 'Filtruj według statusu',
                allStatuses: 'Wszystkie statusy',
                pending: 'Oczekujące',
                confirmed: 'Potwierdzone',
                completed: 'Zrealizowane',
                cancelled: 'Anulowane',
                noShow: 'Nieobecność',
                filterByClient: 'Filtruj według klienta',
                allClients: 'Wszyscy klienci',
                filterByBarber: 'Filtruj według barbera',
                allBarbers: 'Wszyscy barberzy',
                filterByService: 'Filtruj według usługi',
                allServices: 'Wszystkie usługi',
                filterByDate: 'Filtruj według daty',
                colDateTime: 'Data i godzina',
                colClient: 'Klient',
                colBarber: 'Barber',
                colService: 'Usługa',
                colPrice: 'Cena',
                colStatus: 'Status',
                colActions: 'Akcje',
                notFound: 'Nie znaleziono wizyt dla wybranych filtrów.',
                editAppointment: 'Edytuj wizytę',
                selectClient: 'Wybierz klienta',
                selectBarber: 'Wybierz barbera',
                selectService: 'Wybierz usługę',
                dateLabel: 'Data',
                timeLabel: 'Godzina',
                statusLabel: 'Status',
                selectStatus: 'Wybierz status',
                cancel: 'Anuluj',
                saveChanges: 'Zapisz zmiany',
                deleteAppointment: 'Usuń wizytę',
                deleteConfirm: 'Czy na pewno chcesz usunąć tę wizytę? Tej akcji nie można cofnąć.',
                delete: 'Usuń',
                edit: 'Edytuj',
                updated: 'Wizyta zaktualizowana pomyślnie',
                deleted: 'Wizyta usunięta pomyślnie',
                datePrefix: 'Data: ',
                barberPrefix: 'Barber: ',
                servicePrefix: 'Usługa: ',
                validClientRequired: 'Wymagane wskazanie klienta',
                validBarberRequired: 'Wymagane wskazanie barbera',
                validServiceRequired: 'Wymagane wskazanie usługi',
                validDateRequired: 'Data jest wymagana.',
                validTimeFormat: 'Niepoprawny format czasu (HH:mm)',
            },
            services: {
                title: 'Zarządzanie Usługami',
                addNew: 'Dodaj Nową Usługę',
                colName: 'Nazwa',
                colDescription: 'Opis',
                colPrice: 'Cena',
                colDuration: 'Czas trwania (min)',
                colCreated: 'Utworzono',
                colActions: 'Akcje',
                edit: 'Edytuj',
                delete: 'Usuń',
                addDialog: 'Dodaj Nową Usługę',
                addDialogDesc: 'Wypełnij poniższe dane, aby dodać nową usługę.',
                serviceName: 'Nazwa Usługi',
                priceLabel: 'Cena (zł)',
                durationLabel: 'Czas trwania (minuty)',
                cancel: 'Anuluj',
                addButton: 'Dodaj Usługę',
                editDialog: 'Edytuj Usługę',
                editDialogDesc: 'Zmodyfikuj poniższe dane usługi.',
                saveChanges: 'Zapisz Zmiany',
                deleteDialog: 'Usuń Usługę',
                deleteConfirm: 'Czy na pewno chcesz usunąć tę usługę? Ta akcja jest nieodwracalna.',
                namePrefix: 'Nazwa: ',
                pricePrefix: 'Cena: ',
                durationPrefix: 'Czas trwania: ',
                createdPrefix: 'Utworzono: ',
                added: 'Usługa została dodana pomyślnie',
                updated: 'Usługa została zaktualizowana pomyślnie',
                deleted: 'Usługa została usunięta pomyślnie',
                addFailed: 'Nie udało się dodać usługi',
                updateFailed: 'Nie udało się zaktualizować usługi',
                deleteFailed: 'Nie udało się usunąć usługi',
                nameMin: 'Nazwa usługi musi mieć co najmniej 2 znaki',
                descMin: 'Opis musi mieć co najmniej 10 znaków',
                pricePositive: 'Cena musi być dodatnia',
                durationInt: 'Czas trwania musi być liczbą całkowitą',
                durationPositive: 'Czas trwania musi być dodatni',
            },
            reviews: {
                title: 'Zarządzanie opiniami',
                subtitle: 'Przeglądaj oraz zarządzaj opiniami klientów.',
                colClient: 'Klient',
                colBarber: 'Barber',
                colComment: 'Komentarz',
                colRating: 'Ocena',
                colDate: 'Data',
                colActions: 'Akcje',
                deleteReview: 'Usuń opinię',
                deleteConfirm: 'Czy na pewno chcesz usunąć tę recenzję? Tej czynności nie można cofnąć.',
                cancel: 'Anuluj',
                delete: 'Usuń',
                noReviews: 'Nie znaleziono żadnych opinii',
                deleted: 'Opinia została pomyślnie usunięta',
                deleteFailed: 'Nie udało się usunąć opinii',
                barberPrefix: 'Barber: ',
                servicePrefix: 'Usługa: ',
                datePrefix: 'Data: ',
                clientPrefix: 'Klient: ',
                ratingPrefix: 'Ocena: ',
                loadFailed: 'Nie udało się pobrać opinii',
            },
            notifications: {
                title: 'Powiadomienia',
                markAllRead: 'Oznacz wszystkie jako przeczytane',
                newLabel: 'Nowe',
                readLabel: 'Przeczytane',
                none: 'Brak powiadomień do wyświetlenia.',
                show: 'Pokaż',
                invalidDate: 'Nieprawidłowa data',
                details: 'Szczegóły',
                loadFailed: 'Nie udało się pobrać powiadomień',
                markRead: 'Oznacz jako przeczytane',
                markedRead: 'Oznaczono jako przeczytane',
                deleted: 'Powiadomienie usunięte',
                markedAllRead: 'Wszystkie oznaczono jako przeczytane',
                deleteLabel: 'Usuń powiadomienie',
                markReadFailed: 'Nie udało się oznaczyć jako przeczytane na serwerze',
                serverError: 'Błąd serwera. Przywracanie statusu.',
                deleteFailed: 'Nie udało się usunąć powiadomienia na serwerze',
                markAllFailed: 'Nie udało się oznaczyć wszystkich jako przeczytane na serwerze',
            },
            profile: {
                personalInfo: 'Dane osobowe',
                editProfile: 'Edytuj profil',
                save: 'Zapisz',
                cancel: 'Anuluj',
                firstName: 'Imię',
                lastName: 'Nazwisko',
                email: 'E-mail',
                phone: 'Numer telefonu',
                noValue: 'Brak',
                updated: 'Profil został zaktualizowany!',
                goToLogin: 'Przejdź do logowania',
                loadFailed: 'Nie udało się wczytać danych profilu.',
                updateFailed: 'Nie udało się zaktualizować profilu',
                authError: 'Błąd uwierzytelniania.',
                requiredFields: 'Imię, nazwisko i e-mail są wymagane.',
            },
            reports: {
                title: 'Raporty',
                exportPdf: 'Eksportuj PDF',
                timeRange: 'Zakres czasowy',
                today: 'Dzisiaj',
                last7Days: 'Ostatnie 7 dni',
                last30Days: 'Ostatni miesiąc',
                custom: 'Własny zakres',
                from: 'Od',
                to: 'Do',
                apply: 'Zastosuj',
                appointments: 'Wizyty',
                revenue: 'Przychód',
                clients: 'Klienci',
                services: 'Usługi',
                barbers: 'Barberzy',
                status: 'Status',
                loading: 'Ładowanie raportów...',
                noData: 'Brak danych dla wybranego okresu.',
                chartRevenue: 'Przychód (PLN)',
                chartAppointments: 'Liczba wizyt',
                pending: 'Oczekujące',
                confirmed: 'Potwierdzone',
                completed: 'Zrealizowane',
                cancelled: 'Anulowane',
                noShow: 'Nieobecność',
            },
        },
        barberPanel: {
            title: 'Panel Barbera',
            loading: 'Ładowanie panelu barbera...',
            authError: 'Błąd autoryzacji. Zaloguj się.',
            goToLogin: 'Przejdź do logowania',
            appointments: {
                title: 'Zarządzanie wizytami',
                subtitle: 'Przeglądaj i zarządzaj wizytami swoich klientów.',
                filterByTime: 'Filtruj według czasu',
                allTimes: 'Wszystkie czasy',
                upcoming: 'Nadchodzące',
                past: 'Przeszłe',
                filterByStatus: 'Filtruj według statusu',
                allStatuses: 'Wszystkie statusy',
                pending: 'Oczekujące',
                confirmed: 'Potwierdzone',
                completed: 'Zrealizowane',
                cancelled: 'Anulowane',
                noShow: 'Nieobecność',
                colClient: 'Klient',
                colService: 'Usługa',
                colDateTime: 'Data i godzina',
                colPrice: 'Cena',
                colStatus: 'Status',
                colActions: 'Akcje',
                confirm: 'Potwierdź',
                cancel: 'Anuluj',
                complete: 'Zakończ',
                markNoShow: 'Nieobecność',
                markComplete: 'Oznacz jako zakończone',
                markNoShowFull: 'Oznacz jako nieobecność',
                noAppointments: 'Nie znaleziono wizyt',
                noAppointmentsDesc: 'Obecnie nie masz żadnych wizyt.',
                noAppointmentsFilter: 'Brak wizyt spełniających wybrane kryteria.',
                invalidDate: 'Nieprawidłowa data',
                statusUpdated: 'Status wizyty zaktualizowany na',
                updateFailed: 'Nie udało się zaktualizować statusu wizyty',
                loadFailed: 'Nie udało się wczytać wizyt',
                authError: 'Błąd uwierzytelnienia.',
            },
            portfolio: {
                title: 'Galeria portfolio',
                addNew: 'Dodaj nowy obrazek',
                subtitle: 'Pokaż swoje najlepsze prace, aby przyciągnąć klientów.',
                empty: 'Twoje portfolio jest puste',
                emptyDesc: 'Dodaj zdjęcia swoich najlepszych prac, aby zaprezentować swoje umiejętności.',
                addFirst: 'Dodaj pierwszy obrazek',
                addDialog: 'Dodaj nowy obrazek do portfolio',
                addDialogDesc: 'Prześlij zdjęcie, wklej ze schowka lub podaj adres URL.',
                imageUrl: 'Adres URL obrazka',
                urlTab: 'Adres URL',
                uploadTab: 'Prześlij plik',
                pasteTab: 'Schowek',
                clickToUpload: 'Kliknij aby przesłać lub przeciągnij plik',
                pasteHint: 'Naciśnij Ctrl+V aby wkleić zdjęcie ze schowka',
                pasteReady: 'Zdjęcie gotowe do dodania',
                preview: 'Podgląd',
                invalidImage: 'Nieprawidłowy adres URL lub nie udało się wczytać obrazka.',
                titleLabel: 'Tytuł',
                titlePlaceholder: 'np. Klasyczny fade',
                descLabel: 'Opis',
                descPlaceholder: 'np. Czysty fade z teksturowaną górą',
                cancel: 'Anuluj',
                addButton: 'Dodaj do portfolio',
                deleteDialog: 'Usuń obrazek',
                deleteConfirm: 'Czy na pewno chcesz usunąć ten obrazek?',
                deleteButton: 'Usuń obrazek',
                added: 'Obrazek został dodany do portfolio!',
                deleted: 'Obrazek został usunięty z portfolio.',
                addFailed: 'Nie udało się dodać obrazka do portfolio',
                deleteFailed: 'Nie udało się usunąć obrazka',
                uploadFailed: 'Nie udało się przesłać pliku',
                uploadSuccess: 'Plik przesłany pomyślnie',
                urlRequired: 'Adres URL obrazka jest wymagany',
                loadFailed: 'Nie udało się wczytać portfolio',
                authError: 'Aby zobaczyć portfolio, wymagane jest zalogowanie.',
                delete: 'Usuń',
            },
            profile: {
                viewProfile: 'Podgląd profilu',
                editData: 'Edytuj dane',
                editProfile: 'Edytuj profil',
                save: 'Zapisz',
                firstName: 'Imię',
                lastName: 'Nazwisko',
                professionalBarber: 'Profesjonalny barber',
                reviews: 'opinii',
                specializations: 'Specjalizacje:',
                about: 'O mnie:',
                viewPublicProfile: 'Zobacz profil',
                editDetails: 'Edytuj szczegóły profilu',
                profileDetails: 'Szczegóły profilu',
                cancel: 'Anuluj',
                saveChanges: 'Zapisz zmiany',
                accountInfo: 'Informacje o koncie',
                fullName: 'Imię i nazwisko',
                email: 'Email',
                phone: 'Telefon',
                barberData: 'Dane barbera',
                barberDataEditable: 'Dane barbera (edytowalne)',
                aboutMe: 'O mnie',
                noDescription: 'Brak opisu.',
                address: 'Adres',
                workingHours: 'Godziny pracy',
                workingHoursPlaceholder: 'np. 09:00-17:00 (format HH:MM-HH:MM)',
                notProvided: 'Nie podano',
                experience: 'Doświadczenie',
                experiencePlaceholder: 'np. 5 lat',
                specialization: 'Specjalizacje (oddzielone przecinkami)',
                specializationPlaceholder: 'np. fade, trymowanie brody',
                noSpecializations: 'Brak podanych specjalizacji.',
                photoUrl: 'Adres URL zdjęcia profilowego',
                photoPlaceholder: 'https://example.com/zdjecie.jpg',
                uploadPhoto: 'Prześlij zdjęcie profilowe',
                uploadPhotoHint: 'Kliknij aby wybrać zdjęcie',
                photoUrlLabel: 'Lub podaj URL zdjęcia',
                instagram: 'Nazwa użytkownika na Instagramie',
                instagramPlaceholder: 'twoj_instagram',
                facebook: 'Adres profilu na Facebooku',
                facebookPlaceholder: 'https://facebook.com/twojprofil',
                noData: 'Brak danych',
                backToOverview: 'Wróć do podsumowania',
                updated: 'Profil został pomyślnie zaktualizowany!',
                updateFailed: 'Nie udało się zaktualizować profilu',
                loadFailed: 'Nie udało się wczytać profilu',
                authError: 'Błąd uwierzytelniania lub brak danych profilu.',
                uploadFailed: 'Nie udało się przesłać zdjęcia',
            },
            notifications: {
                title: 'Moje powiadomienia',
                newBadge: 'NOWE',
                markAllRead: 'Oznacz wszystkie jako przeczytane',
                subtitle: 'Przeglądaj i zarządzaj powiadomieniami związanymi z Twoją pracą.',
                all: 'Wszystkie',
                unread: 'Nieprzeczytane',
                allRead: 'Wszystkie powiadomienia zostały przeczytane.',
                allDone: 'Wszystko przeczytane! Nowe powiadomienia pojawią się tutaj.',
                noNotifications: 'Brak powiadomień do wyświetlenia.',
                noneInCategory: 'Brak powiadomień w tej kategorii.',
                markRead: 'Oznacz jako przeczytane',
                deleteNotification: 'Usuń powiadomienie',
                viewDetails: 'Szczegóły',
                loadFailed: 'Nie udało się pobrać powiadomień barbera',
                authError: 'Błąd autoryzacji. Proszę się zalogować.',
                markReadFailed: 'Nie udało się oznaczyć jako przeczytane',
                deleteFailed: 'Nie udało się usunąć powiadomienia',
                markAllFailed: 'Nie udało się oznaczyć wszystkich jako przeczytane',
            },
            schedule: {
                selectDate: 'Wybierz datę',
                selectDateDesc: 'Zobacz wizyty dla wybranego dnia.',
                latestNotifications: 'Ostatnie powiadomienia',
                notificationsDesc: 'Twoje najnowsze powiadomienia.',
                invalidDate: 'Nieprawidłowa data',
                viewAllNotifications: 'Zobacz wszystkie powiadomienia',
                noNewNotifications: 'Brak nowych powiadomień.',
                appointmentsFor: 'Wizyty na',
                appointmentsDesc: 'Zaplanowane wizyty na wybrany dzień.',
                loadingAppointments: 'Ładowanie wizyt...',
                noAppointments: 'Twój grafik jest pusty w tym dniu.',
                invalidTime: 'Nieprawidłowa godzina',
                loadFailed: 'Nie udało się wczytać harmonogramu dnia',
                authError: 'Błąd autoryzacji. Zaloguj się.',
            },
        },
        userPanel: {
            title: 'Panel klienta',
            loading: 'Ładowanie panelu...',
            authError: 'Błąd uwierzytelniania',
            authErrorDesc: 'Błąd uwierzytelniania. Zaloguj się, aby kontynuować.',
            goToLogin: 'Przejdź do logowania',
            overview: {
                greeting: 'Cześć',
                welcomeMsg: 'Witaj w swoim panelu. Oto podsumowanie Twojej aktywności.',
                appointmentCount: 'Liczba wizyt',
                excludingCancelled: 'Z wyłączeniem anulowanych',
                averageRating: 'Średnia ocen',
                noRating: 'Brak',
                averageRatingLabel: 'Średnia ocena wizyt',
                quickBooking: 'Szybka rezerwacja',
                findSlot: 'Znajdź termin',
                nextAppointment: 'Najbliższa wizyta',
                with: 'u',
                reschedule: 'Przełóż wizytę (wkrótce)',
                noUpcoming: 'Nie masz nadchodzących wizyt.',
                bookAppointment: 'Zarezerwuj wizytę',
                latestNotifications: 'Ostatnie powiadomienia',
                noNotifications: 'Brak ostatnich powiadomień.',
                viewAllNotifications: 'Zobacz wszystkie powiadomienia',
                loadError: 'Wystąpił błąd podczas ładowania danych panelu.',
            },
            appointments: {
                title: 'Moje wizyty',
                subtitle: 'Zarządzaj swoimi nadchodzącymi i przeszłymi wizytami.',
                bookNew: 'Zarezerwuj nową wizytę',
                filterByStatus: 'Filtruj wg statusu:',
                all: 'Wszystkie',
                pending: 'Oczekujące',
                confirmed: 'Potwierdzone',
                completed: 'Zrealizowane',
                cancelled: 'Anulowane',
                noShow: 'Nieobecność',
                barberLabel: 'Barber: ',
                cancelAppointment: 'Anuluj wizytę',
                reschedule: 'Przełóż wizytę',
                addReview: 'Dodaj opinię',
                noAppointments: 'Nie znaleziono wizyt',
                noAppointmentsYet: 'Nie masz jeszcze żadnych zarezerwowanych wizyt.',
                noAppointmentsFilter: 'Nie masz wizyt ze statusem:',
                bookFirst: 'Zarezerwuj swoją pierwszą wizytę',
                invalidDate: 'Nieprawidłowa data',
                cancelledSuccess: 'Wizyta została pomyślnie anulowana.',
                cancelFailed: 'Nie udało się anulować wizyty',
                loadFailed: 'Nie udało się wczytać wizyt.',
                authError: 'Błąd uwierzytelniania. Nie można anulować wizyty.',
            },
            profile: {
                personalInfo: 'Dane osobowe',
                editProfile: 'Edytuj profil',
                save: 'Zapisz',
                cancel: 'Anuluj',
                firstName: 'Imię',
                lastName: 'Nazwisko',
                email: 'E-mail',
                phone: 'Numer telefonu',
                enterPhone: 'Wprowadź numer telefonu',
                noValue: 'Brak',
                updated: 'Profil został pomyślnie zaktualizowany!',
                required: 'Imię, nazwisko i adres e-mail są wymagane.',
                loadFailed: 'Nie udało się wczytać danych profilu.',
                updateFailed: 'Nie udało się zaktualizować profilu',
                authError: 'Błąd uwierzytelniania. Zaloguj się ponownie.',
            },
            reviews: {
                summary: 'Podsumowanie Twoich opinii',
                summaryDesc: 'Krótkie statystyki dotyczące Twoich dotychczasowych ocen.',
                count: 'Liczba wystawionych opinii',
                outOf: '/ 5.0',
                avgRating: 'Średnia ocena',
                writeNew: 'Napisz nową opinię',
                addReview: 'Dodaj opinię',
                addReviewDesc: 'Podziel się swoją opinią na temat zakończonej wizyty.',
                appointmentToReview: 'Wizyta do oceny',
                selectAppointment: 'Wybierz zakończoną wizytę',
                noAppointmentsToReview: 'Brak nowych wizyt do oceny.',
                yourRating: 'Twoja ocena',
                yourComment: 'Twój komentarz',
                commentPlaceholder: 'Opisz swoje doświadczenie z wizyty...',
                cancel: 'Anuluj',
                submit: 'Wyślij opinię',
                noNewToReview: 'Nie masz obecnie nowych wizyt do oceny.',
                myReviews: 'Moje dotychczasowe opinie',
                addedPrefix: 'Dodano: ',
                noData: 'Brak danych',
                barberLabel: 'Barber: ',
                noReviews: 'Nie dodałeś jeszcze żadnej opinii.',
                noReviewsDesc: 'Po swojej następnej wizycie podziel się doświadczeniem!',
                added: 'Opinia została pomyślnie dodana!',
                addFailed: 'Nie udało się dodać opinii',
                loadFailed: 'Nie udało się wczytać Twoich opinii.',
                authError: 'Błąd uwierzytelniania.',
                selectVisit: 'Wybierz wizytę, którą chcesz ocenić.',
                provideRating: 'Podaj ocenę w skali 1–5 gwiazdek.',
                writeComment: 'Napisz komentarz do swojej opinii.',
            },
            notifications: {
                title: 'Powiadomienia',
                newBadge: 'nowe',
                markAllRead: 'Oznacz wszystkie jako przeczytane',
                noNotifications: 'Brak powiadomień',
                allDone: 'Wszystko nadrobione! Nowe powiadomienia pojawią się tutaj.',
                markedAllRead: 'Wszystkie powiadomienia oznaczono jako przeczytane.',
                deleted: 'Powiadomienie zostało usunięte.',
                loadFailed: 'Nie udało się wczytać powiadomień.',
                markReadFailed: 'Nie udało się oznaczyć powiadomienia jako przeczytane',
                markAllFailed: 'Nie udało się oznaczyć wszystkich jako przeczytane',
                deleteFailed: 'Nie udało się usunąć powiadomienia',
                authError: 'Błąd uwierzytelniania.',
            },
        },
        bookingPage: {
            title: 'Zarezerwuj wizytę',
            subtitle: 'Wybierz usługę, barbera i termin który Ci odpowiada.',
            step1: 'Usługa',
            step2: 'Barber',
            step3: 'Termin',
            step4: 'Dane',
            step5: 'Potwierdzenie',
            selectService: 'Wybierz usługę',
            selectBarber: 'Wybierz barbera',
            selectDate: 'Wybierz datę',
            selectTime: 'Wybierz godzinę',
            yourDetails: 'Twoje dane',
            firstName: 'Imię',
            lastName: 'Nazwisko',
            email: 'E-mail',
            notes: 'Uwagi',
            notesPlaceholder: 'Dodatkowe informacje...',
            termsAccept: 'Akceptuję regulamin',
            confirm: 'Potwierdź rezerwację',
            back: 'Wstecz',
            next: 'Dalej',
            bookingConfirmed: 'Rezerwacja potwierdzona!',
            bookingFailed: 'Nie udało się zarezerwować wizyty.',
            loadingServices: 'Ładowanie usług...',
            loadingBarbers: 'Ładowanie barberów...',
            loadingSlots: 'Ładowanie dostępnych terminów...',
            noSlots: 'Brak dostępnych terminów na wybrany dzień.',
            anyBarber: 'Dowolny barber',
            duration: 'min',
            price: 'Cena',
            summary: 'Podsumowanie rezerwacji',
            service: 'Usługa',
            barber: 'Barber',
            date: 'Data',
            time: 'Godzina',
            loginRequired: 'Zaloguj się, aby zarezerwować wizytę.',
        },
    },
    en: {
        nav: {
            home: 'Home',
            services: 'Services',
            team: 'Team',
            reviews: 'Reviews',
            bookAppointment: 'Book Appointment',
            account: 'Account',
            profile: 'Profile',
            dashboard: 'Dashboard',
            logout: 'Sign Out',
            login: 'Sign In',
            register: 'Sign Up',
        },
        adminMenu: {
            overview: 'Overview',
            users: 'Users',
            appointments: 'Appointments',
            services: 'Services',
            reviews: 'Reviews',
        },
        home: {
            heroTitle: 'Classic cuts',
            heroSubtitle: 'in modern style',
            heroDescription: 'Premium barbering services for the discerning man. Experience perfect grooming in a relaxed yet professional atmosphere.',
            bookNow: 'Book Appointment',
            ourServices: 'Our Services',
            whyChooseUs: 'Why choose our barbershop?',
            whySubtitle: 'We combine classic barbering craft with modern style, delivering top-tier services by an experienced team.',
            feature1Title: 'Experienced Barbers',
            feature1Desc: 'Our team consists of skilled specialists with years of experience in both modern and classic cutting techniques.',
            feature2Title: 'Easy Booking',
            feature2Desc: 'Our online booking system makes it easy to schedule an appointment at a time that suits you — 24/7.',
            feature3Title: 'Premium Services',
            feature3Desc: 'From classic cuts and beard sculpting to hot towels — we offer a wide range of services tailored to your needs.',
            feature4Title: 'Quality Products',
            feature4Desc: 'We use only trusted professional hair and beard products to ensure the best results and long-lasting effects.',
            ctaTitle: 'Ready for a fresh new look?',
            ctaDescription: 'Book an appointment today and take advantage of our premium services. Looking great has never been this easy.',
            ctaButton: 'Book Now',
            ctaImageAlt: 'Barbershop interior',
        },
        footer: {
            tagline: 'Premium services for men. Experience barbering tradition in a modern setting.',
            quickLinks: 'Quick Links',
            team: 'Our Team',
            servicesTitle: 'Services',
            haircut: 'Haircut',
            beardTrim: 'Beard Trim',
            hotTowelShave: 'Hot Towel Shave',
            hairColoring: 'Hair Coloring',
            kidsHaircut: "Kids' Haircut",
            contact: 'Contact',
            allRightsReserved: 'All rights reserved.',
            privacyPolicy: 'Privacy Policy',
            terms: 'Terms of Service',
            contactUs: 'Contact Us',
        },
        dashboard: {
            welcome: 'Welcome',
            overview: 'Overview',
            appointments: 'Appointments',
            profile: 'Profile',
            reviews: 'Reviews',
            notifications: 'Notifications',
            schedule: 'Schedule',
            portfolio: 'Portfolio',
            users: 'Users',
            services: 'Services',
            reports: 'Reports',
            logout: 'Sign Out',
            adminPanel: 'Admin Panel',
            barberPanel: 'Barber Panel',
            clientPanel: 'Client Panel',
        },
        services: {
            title: 'Our Services',
            subtitle: 'From classic cuts to premium grooming treatments – we offer a wide range of services tailored to the modern man.',
            bookAppointment: 'Book Appointment',
            loading: 'Loading services...',
            noServices: 'No services available at the moment.',
            noServicesHint: 'Check back later.',
            duration: 'min',
        },
        team: {
            title: 'Our Team',
            heroTitle: 'Meet our team',
            subtitle: 'Meet our skilled specialists who will take care of your appearance.',
            heroSubtitle: 'Our barbers and stylists combine years of experience with passion, paying attention to every detail of your visit.',
            experience: 'years of experience',
            bookWith: 'Book with',
            seePortfolio: 'See portfolio',
            allSpecializations: 'All',
            searchPlaceholder: 'Search by name or role...',
            viewProfile: 'View profile',
            loading: 'Loading team members...',
            noMembers: 'No team members match your search criteria.',
            noMembersHint: 'Try changing your search or filters.',
            specializations: 'Specializations',
            certifications: 'Certifications',
            contact: 'Contact',
            portfolioTitle: 'Portfolio',
            about: 'About',
            noDescription: 'No description added.',
            bookWithPerson: 'Book appointment with',
            photoOf: 'Photo',
            of: 'of',
            noPhotos: 'No photos to display.',
            notFound: 'Could not load barber details or barber was not found.',
        },
        reviews: {
            title: 'Customer Reviews',
            subtitle: 'See what our clients say about their visits to our barbershop.',
            ratingSummary: 'Rating Summary',
            totalReviews: 'reviews total',
            reviewCount: 'reviews',
            searchPlaceholder: 'Search reviews...',
            filterAll: 'All ratings',
            sortNewest: 'Newest',
            sortHighest: 'Highest rated',
            sortLowest: 'Lowest rated',
            loading: 'Loading reviews...',
            helpful: 'Helpful',
            unhelpful: 'Not helpful',
            noReviews: 'No reviews found matching your criteria.',
            clearFilters: 'Clear filters',
            beFirst: 'Be the first to review our services!',
            barberLabel: 'barber',
            starSingular: 'star',
            starFew: 'stars',
            starMany: 'stars',
            invalidDate: 'Invalid date',
        },
        booking: {
            title: 'Book an Appointment',
            subtitle: 'Choose a service, barber, and time that suits you.',
        },
        auth: {
            loginTitle: 'Sign In',
            loginWelcome: 'Welcome back',
            loginSubtitle: 'Enter your credentials to access your account.',
            loginSubtitleFull: 'Enter your email and password to access your account',
            registerTitle: 'Create Account',
            registerSubtitle: 'Sign up to book appointments.',
            registerSubtitleFull: 'Enter your details to create a new account',
            email: 'Email address',
            password: 'Password',
            firstName: 'First name',
            lastName: 'Last name',
            phone: 'Phone number',
            loginButton: 'Sign In',
            registerButton: 'Sign Up',
            noAccount: "Don't have an account?",
            hasAccount: 'Already have an account?',
            signUpLink: 'Sign Up',
            signInLink: 'Sign In',
            forgotPassword: 'Forgot your password?',
            loggingIn: 'Signing in...',
            creatingAccount: 'Creating account...',
            confirmPassword: 'Confirm password',
            or: 'Or',
            emailRequired: 'Email is required',
            emailInvalid: 'Invalid email address',
            passwordRequired: 'Password is required',
            passwordMin: 'Password must be at least 6 characters',
            firstNameRequired: 'First name is required',
            lastNameRequired: 'Last name is required',
            phoneRequired: 'Phone number is required',
            passwordsMismatch: 'Passwords do not match',
            loginFailed: 'Login failed. Check your credentials and try again.',
            registerFailed: 'Registration failed. Please try again.',
        },
        common: {
            loading: 'Loading...',
            save: 'Save',
            cancel: 'Cancel',
            edit: 'Edit',
            delete: 'Delete',
            confirm: 'Confirm',
            back: 'Back',
            close: 'Close',
        },
        adminPanel: {
            title: 'Admin Panel',
            loading: 'Loading...',
            authError: 'Authorization error. Please sign in.',
            overview: {
                visitsByCount: 'Appointments (count)',
                revenue: 'Revenue (PLN)',
                users: 'Users',
                activeAppointments: 'Active Appointments',
                allServices: 'All Services',
                monthlyRevenue: 'Monthly Revenue',
                todayCompleted: 'Completed appointments today',
                todayChartDesc: 'Hourly breakdown of completed appointments and revenue.',
                hour: 'Hour',
                appointmentCount: 'Appointment count',
                revenueLabel: 'Revenue (PLN)',
                noDataToday: 'No completed appointments or revenue recorded today.',
                notifications: 'Notifications',
                latestNotifications: 'Latest important notifications.',
                noNewNotifications: 'No new notifications',
                errorStats: 'Failed to load general statistics.',
                errorActivity: 'Failed to load today\'s activity.',
                errorNotifications: 'Failed to load notifications.',
                errorDashboard: 'Failed to load dashboard data.',
            },
            users: {
                title: 'User Management',
                subtitle: 'Browse, edit and manage all users in the system.',
                filterByRole: 'Filter by role',
                allRoles: 'All roles',
                clients: 'Clients',
                barbersLabel: 'Barbers',
                admins: 'Administrators',
                colName: 'Full Name',
                colEmail: 'Email',
                colPhone: 'Phone',
                colRole: 'Role',
                colCreated: 'Created',
                colActions: 'Actions',
                noValue: 'N/A',
                roleAdmin: 'Administrator',
                roleBarber: 'Barber',
                roleClient: 'Client',
                editUser: 'Edit User',
                editUserDesc: 'Update user details and their role.',
                firstName: 'First Name',
                lastName: 'Last Name',
                roleLabel: 'Role',
                cancel: 'Cancel',
                saveChanges: 'Save Changes',
                deleteUser: 'Delete User',
                deleteUserConfirm: 'Are you sure you want to delete this user? This action cannot be undone.',
                delete: 'Delete',
                updated: 'User updated successfully.',
                deleted: 'User deleted successfully.',
                firstNameMin: 'First name must be at least 2 characters.',
                lastNameMin: 'Last name must be at least 2 characters.',
                invalidEmail: 'Invalid email address.',
                updateFailed: 'Update failed.',
                deleteFailed: 'Failed to delete user.',
                loadFailed: 'Failed to load users.',
                phoneLabel: 'Phone: ',
                createdLabel: 'Created: ',
                fullNameLabel: 'Full Name: ',
            },
            appointments: {
                title: 'Appointment Management',
                clearFilters: 'Clear Filters',
                filterByStatus: 'Filter by status',
                allStatuses: 'All statuses',
                pending: 'Pending',
                confirmed: 'Confirmed',
                completed: 'Completed',
                cancelled: 'Cancelled',
                noShow: 'No Show',
                filterByClient: 'Filter by client',
                allClients: 'All clients',
                filterByBarber: 'Filter by barber',
                allBarbers: 'All barbers',
                filterByService: 'Filter by service',
                allServices: 'All services',
                filterByDate: 'Filter by date',
                colDateTime: 'Date & Time',
                colClient: 'Client',
                colBarber: 'Barber',
                colService: 'Service',
                colPrice: 'Price',
                colStatus: 'Status',
                colActions: 'Actions',
                notFound: 'No appointments found for the selected filters.',
                editAppointment: 'Edit Appointment',
                selectClient: 'Select client',
                selectBarber: 'Select barber',
                selectService: 'Select service',
                dateLabel: 'Date',
                timeLabel: 'Time',
                statusLabel: 'Status',
                selectStatus: 'Select status',
                cancel: 'Cancel',
                saveChanges: 'Save Changes',
                deleteAppointment: 'Delete Appointment',
                deleteConfirm: 'Are you sure you want to delete this appointment? This action cannot be undone.',
                delete: 'Delete',
                edit: 'Edit',
                updated: 'Appointment updated successfully',
                deleted: 'Appointment deleted successfully',
                datePrefix: 'Date: ',
                barberPrefix: 'Barber: ',
                servicePrefix: 'Service: ',
                validClientRequired: 'Client is required',
                validBarberRequired: 'Barber is required',
                validServiceRequired: 'Service is required',
                validDateRequired: 'Date is required.',
                validTimeFormat: 'Invalid time format (HH:mm)',
            },
            services: {
                title: 'Service Management',
                addNew: 'Add New Service',
                colName: 'Name',
                colDescription: 'Description',
                colPrice: 'Price',
                colDuration: 'Duration (min)',
                colCreated: 'Created',
                colActions: 'Actions',
                edit: 'Edit',
                delete: 'Delete',
                addDialog: 'Add New Service',
                addDialogDesc: 'Fill in the details below to add a new service.',
                serviceName: 'Service Name',
                priceLabel: 'Price (PLN)',
                durationLabel: 'Duration (minutes)',
                cancel: 'Cancel',
                addButton: 'Add Service',
                editDialog: 'Edit Service',
                editDialogDesc: 'Modify the service details below.',
                saveChanges: 'Save Changes',
                deleteDialog: 'Delete Service',
                deleteConfirm: 'Are you sure you want to delete this service? This action is irreversible.',
                namePrefix: 'Name: ',
                pricePrefix: 'Price: ',
                durationPrefix: 'Duration: ',
                createdPrefix: 'Created: ',
                added: 'Service added successfully',
                updated: 'Service updated successfully',
                deleted: 'Service deleted successfully',
                addFailed: 'Failed to add service',
                updateFailed: 'Failed to update service',
                deleteFailed: 'Failed to delete service',
                nameMin: 'Service name must be at least 2 characters',
                descMin: 'Description must be at least 10 characters',
                pricePositive: 'Price must be positive',
                durationInt: 'Duration must be a whole number',
                durationPositive: 'Duration must be positive',
            },
            reviews: {
                title: 'Review Management',
                subtitle: 'Browse and manage customer reviews.',
                colClient: 'Client',
                colBarber: 'Barber',
                colComment: 'Comment',
                colRating: 'Rating',
                colDate: 'Date',
                colActions: 'Actions',
                deleteReview: 'Delete Review',
                deleteConfirm: 'Are you sure you want to delete this review? This action cannot be undone.',
                cancel: 'Cancel',
                delete: 'Delete',
                noReviews: 'No reviews found',
                deleted: 'Review deleted successfully',
                deleteFailed: 'Failed to delete review',
                barberPrefix: 'Barber: ',
                servicePrefix: 'Service: ',
                datePrefix: 'Date: ',
                clientPrefix: 'Client: ',
                ratingPrefix: 'Rating: ',
                loadFailed: 'Failed to load reviews',
            },
            notifications: {
                title: 'Notifications',
                markAllRead: 'Mark all as read',
                newLabel: 'New',
                readLabel: 'Read',
                none: 'No notifications to display.',
                show: 'Show',
                invalidDate: 'Invalid date',
                details: 'Details',
                loadFailed: 'Failed to load notifications',
                markRead: 'Mark as read',
                markedRead: 'Marked as read',
                deleted: 'Notification deleted',
                markedAllRead: 'All notifications marked as read',
                deleteLabel: 'Delete notification',
                markReadFailed: 'Failed to mark as read on server',
                serverError: 'Server error. Restoring status.',
                deleteFailed: 'Failed to delete notification on server',
                markAllFailed: 'Failed to mark all as read on server',
            },
            profile: {
                personalInfo: 'Personal Information',
                editProfile: 'Edit Profile',
                save: 'Save',
                cancel: 'Cancel',
                firstName: 'First Name',
                lastName: 'Last Name',
                email: 'Email',
                phone: 'Phone Number',
                noValue: 'N/A',
                updated: 'Profile updated successfully!',
                goToLogin: 'Go to Sign In',
                loadFailed: 'Failed to load profile data.',
                updateFailed: 'Failed to update profile',
                authError: 'Authentication error.',
                requiredFields: 'First name, last name and email are required.',
            },
            reports: {
                title: 'Reports',
                exportPdf: 'Export PDF',
                timeRange: 'Time Range',
                today: 'Today',
                last7Days: 'Last 7 Days',
                last30Days: 'Last 30 Days',
                custom: 'Custom Range',
                from: 'From',
                to: 'To',
                apply: 'Apply',
                appointments: 'Appointments',
                revenue: 'Revenue',
                clients: 'Clients',
                services: 'Services',
                barbers: 'Barbers',
                status: 'Status',
                loading: 'Loading reports...',
                noData: 'No data available for the selected period.',
                chartRevenue: 'Revenue (PLN)',
                chartAppointments: 'Appointment count',
                pending: 'Pending',
                confirmed: 'Confirmed',
                completed: 'Completed',
                cancelled: 'Cancelled',
                noShow: 'No Show',
            },
        },
        barberPanel: {
            title: 'Barber Panel',
            loading: 'Loading barber panel...',
            authError: 'Authorization error. Please sign in.',
            goToLogin: 'Go to Sign In',
            appointments: {
                title: 'Appointment Management',
                subtitle: 'View and manage your client appointments.',
                filterByTime: 'Filter by time',
                allTimes: 'All times',
                upcoming: 'Upcoming',
                past: 'Past',
                filterByStatus: 'Filter by status',
                allStatuses: 'All statuses',
                pending: 'Pending',
                confirmed: 'Confirmed',
                completed: 'Completed',
                cancelled: 'Cancelled',
                noShow: 'No Show',
                colClient: 'Client',
                colService: 'Service',
                colDateTime: 'Date & Time',
                colPrice: 'Price',
                colStatus: 'Status',
                colActions: 'Actions',
                confirm: 'Confirm',
                cancel: 'Cancel',
                complete: 'Complete',
                markNoShow: 'No Show',
                markComplete: 'Mark as completed',
                markNoShowFull: 'Mark as no show',
                noAppointments: 'No appointments found',
                noAppointmentsDesc: 'You have no appointments at this time.',
                noAppointmentsFilter: 'No appointments matching the selected criteria.',
                invalidDate: 'Invalid date',
                statusUpdated: 'Appointment status updated to',
                updateFailed: 'Failed to update appointment status',
                loadFailed: 'Failed to load appointments',
                authError: 'Authentication error.',
            },
            portfolio: {
                title: 'Portfolio Gallery',
                addNew: 'Add New Image',
                subtitle: 'Showcase your best work to attract clients.',
                empty: 'Your portfolio is empty',
                emptyDesc: 'Add photos of your best work to showcase your skills.',
                addFirst: 'Add First Image',
                addDialog: 'Add New Portfolio Image',
                addDialogDesc: 'Upload a file, paste from clipboard, or enter an image URL.',
                imageUrl: 'Image URL',
                urlTab: 'Image URL',
                uploadTab: 'Upload File',
                pasteTab: 'Clipboard',
                clickToUpload: 'Click to upload or drag and drop',
                pasteHint: 'Press Ctrl+V to paste image from clipboard',
                pasteReady: 'Image ready to add',
                preview: 'Preview',
                invalidImage: 'Invalid URL or failed to load image.',
                titleLabel: 'Title',
                titlePlaceholder: 'e.g. Classic Fade',
                descLabel: 'Description',
                descPlaceholder: 'e.g. Clean fade with textured top',
                cancel: 'Cancel',
                addButton: 'Add to Portfolio',
                deleteDialog: 'Delete Image',
                deleteConfirm: 'Are you sure you want to delete this image?',
                deleteButton: 'Delete Image',
                added: 'Image added to portfolio!',
                deleted: 'Image removed from portfolio.',
                addFailed: 'Failed to add image to portfolio',
                deleteFailed: 'Failed to delete image',
                uploadFailed: 'Failed to upload file',
                uploadSuccess: 'File uploaded successfully',
                urlRequired: 'Image URL is required',
                loadFailed: 'Failed to load portfolio',
                authError: 'Sign in required to view portfolio.',
                delete: 'Delete',
            },
            profile: {
                viewProfile: 'Profile Preview',
                editData: 'Edit Details',
                editProfile: 'Edit Profile',
                save: 'Save',
                firstName: 'First Name',
                lastName: 'Last Name',
                professionalBarber: 'Professional Barber',
                reviews: 'reviews',
                specializations: 'Specializations:',
                about: 'About me:',
                viewPublicProfile: 'View Profile',
                editDetails: 'Edit Profile Details',
                profileDetails: 'Profile Details',
                cancel: 'Cancel',
                saveChanges: 'Save Changes',
                accountInfo: 'Account Information',
                fullName: 'Full Name',
                email: 'Email',
                phone: 'Phone',
                barberData: 'Barber Details',
                barberDataEditable: 'Barber Details (editable)',
                aboutMe: 'About Me',
                noDescription: 'No description added.',
                address: 'Address',
                workingHours: 'Working Hours',
                workingHoursPlaceholder: 'e.g. 09:00-17:00 (HH:MM-HH:MM)',
                notProvided: 'Not provided',
                experience: 'Experience',
                experiencePlaceholder: 'e.g. 5 years',
                specialization: 'Specializations (comma-separated)',
                specializationPlaceholder: 'e.g. fade, beard trim',
                noSpecializations: 'No specializations listed.',
                photoUrl: 'Profile Photo URL',
                photoPlaceholder: 'https://example.com/photo.jpg',
                uploadPhoto: 'Upload Profile Photo',
                uploadPhotoHint: 'Click to select a photo',
                photoUrlLabel: 'Or enter photo URL',
                instagram: 'Instagram Username',
                instagramPlaceholder: 'your_instagram',
                facebook: 'Facebook Profile URL',
                facebookPlaceholder: 'https://facebook.com/yourprofile',
                noData: 'No data',
                backToOverview: 'Back to overview',
                updated: 'Profile updated successfully!',
                updateFailed: 'Failed to update profile',
                loadFailed: 'Failed to load profile',
                authError: 'Authentication error or profile data missing.',
                uploadFailed: 'Failed to upload photo',
            },
            notifications: {
                title: 'My Notifications',
                newBadge: 'NEW',
                markAllRead: 'Mark all as read',
                subtitle: 'Browse and manage notifications related to your work.',
                all: 'All',
                unread: 'Unread',
                allRead: 'All notifications have been read.',
                allDone: 'All caught up! New notifications will appear here.',
                noNotifications: 'No notifications to display.',
                noneInCategory: 'No notifications in this category.',
                markRead: 'Mark as read',
                deleteNotification: 'Delete notification',
                viewDetails: 'Details',
                loadFailed: 'Failed to load notifications',
                authError: 'Authorization error. Please sign in.',
                markReadFailed: 'Failed to mark as read',
                deleteFailed: 'Failed to delete notification',
                markAllFailed: 'Failed to mark all as read',
            },
            schedule: {
                selectDate: 'Select Date',
                selectDateDesc: 'View appointments for the selected day.',
                latestNotifications: 'Latest Notifications',
                notificationsDesc: 'Your most recent notifications.',
                invalidDate: 'Invalid date',
                viewAllNotifications: 'View all notifications',
                noNewNotifications: 'No new notifications.',
                appointmentsFor: 'Appointments for',
                appointmentsDesc: 'Scheduled appointments for the selected day.',
                loadingAppointments: 'Loading appointments...',
                noAppointments: 'Your schedule is empty for this day.',
                invalidTime: 'Invalid time',
                loadFailed: 'Failed to load daily schedule',
                authError: 'Authorization error. Please sign in.',
            },
        },
        userPanel: {
            title: 'Client Panel',
            loading: 'Loading panel...',
            authError: 'Authentication error',
            authErrorDesc: 'Authentication error. Please sign in to continue.',
            goToLogin: 'Go to Sign In',
            overview: {
                greeting: 'Hello',
                welcomeMsg: 'Welcome to your dashboard. Here\'s a summary of your activity.',
                appointmentCount: 'Appointment Count',
                excludingCancelled: 'Excluding cancelled',
                averageRating: 'Average Rating',
                noRating: 'N/A',
                averageRatingLabel: 'Your average appointment rating',
                quickBooking: 'Quick Booking',
                findSlot: 'Find a slot',
                nextAppointment: 'Next Appointment',
                with: 'with',
                reschedule: 'Reschedule (coming soon)',
                noUpcoming: 'You have no upcoming appointments.',
                bookAppointment: 'Book Appointment',
                latestNotifications: 'Latest Notifications',
                noNotifications: 'No recent notifications.',
                viewAllNotifications: 'View all notifications',
                loadError: 'An error occurred while loading dashboard data.',
            },
            appointments: {
                title: 'My Appointments',
                subtitle: 'Manage your upcoming and past appointments.',
                bookNew: 'Book New Appointment',
                filterByStatus: 'Filter by status:',
                all: 'All',
                pending: 'Pending',
                confirmed: 'Confirmed',
                completed: 'Completed',
                cancelled: 'Cancelled',
                noShow: 'No Show',
                barberLabel: 'Barber: ',
                cancelAppointment: 'Cancel Appointment',
                reschedule: 'Reschedule',
                addReview: 'Add Review',
                noAppointments: 'No appointments found',
                noAppointmentsYet: 'You have no booked appointments yet.',
                noAppointmentsFilter: 'You have no appointments with status:',
                bookFirst: 'Book your first appointment',
                invalidDate: 'Invalid date',
                cancelledSuccess: 'Appointment cancelled successfully.',
                cancelFailed: 'Failed to cancel appointment',
                loadFailed: 'Failed to load appointments.',
                authError: 'Authentication error. Cannot cancel appointment.',
            },
            profile: {
                personalInfo: 'Personal Information',
                editProfile: 'Edit Profile',
                save: 'Save',
                cancel: 'Cancel',
                firstName: 'First Name',
                lastName: 'Last Name',
                email: 'Email',
                phone: 'Phone Number',
                enterPhone: 'Enter phone number',
                noValue: 'N/A',
                updated: 'Profile updated successfully!',
                required: 'First name, last name and email are required.',
                loadFailed: 'Failed to load profile data.',
                updateFailed: 'Failed to update profile',
                authError: 'Authentication error. Please sign in again.',
            },
            reviews: {
                summary: 'Your Review Summary',
                summaryDesc: 'Brief statistics about your ratings so far.',
                count: 'Reviews submitted',
                outOf: '/ 5.0',
                avgRating: 'Average rating',
                writeNew: 'Write New Review',
                addReview: 'Add Review',
                addReviewDesc: 'Share your feedback about a completed appointment.',
                appointmentToReview: 'Appointment to Review',
                selectAppointment: 'Select a completed appointment',
                noAppointmentsToReview: 'No new appointments to review.',
                yourRating: 'Your Rating',
                yourComment: 'Your Comment',
                commentPlaceholder: 'Describe your experience...',
                cancel: 'Cancel',
                submit: 'Submit Review',
                noNewToReview: 'You have no new appointments to review at this time.',
                myReviews: 'My Reviews',
                addedPrefix: 'Added: ',
                noData: 'No data',
                barberLabel: 'Barber: ',
                noReviews: 'You haven\'t submitted any reviews yet.',
                noReviewsDesc: 'After your next appointment, share your experience!',
                added: 'Review submitted successfully!',
                addFailed: 'Failed to submit review',
                loadFailed: 'Failed to load your reviews.',
                authError: 'Authentication error.',
                selectVisit: 'Select an appointment to review.',
                provideRating: 'Provide a rating from 1 to 5 stars.',
                writeComment: 'Write a comment for your review.',
            },
            notifications: {
                title: 'Notifications',
                newBadge: 'new',
                markAllRead: 'Mark all as read',
                noNotifications: 'No notifications',
                allDone: 'All caught up! New notifications will appear here.',
                markedAllRead: 'All notifications marked as read.',
                deleted: 'Notification deleted.',
                loadFailed: 'Failed to load notifications.',
                markReadFailed: 'Failed to mark notification as read',
                markAllFailed: 'Failed to mark all as read',
                deleteFailed: 'Failed to delete notification',
                authError: 'Authentication error.',
            },
        },
        bookingPage: {
            title: 'Book an Appointment',
            subtitle: 'Choose a service, barber, and time that works for you.',
            step1: 'Service',
            step2: 'Barber',
            step3: 'Date',
            step4: 'Details',
            step5: 'Confirmation',
            selectService: 'Select a service',
            selectBarber: 'Select a barber',
            selectDate: 'Select a date',
            selectTime: 'Select a time',
            yourDetails: 'Your Details',
            firstName: 'First Name',
            lastName: 'Last Name',
            email: 'Email',
            notes: 'Notes',
            notesPlaceholder: 'Additional information...',
            termsAccept: 'I accept the terms and conditions',
            confirm: 'Confirm Booking',
            back: 'Back',
            next: 'Next',
            bookingConfirmed: 'Booking confirmed!',
            bookingFailed: 'Failed to book appointment.',
            loadingServices: 'Loading services...',
            loadingBarbers: 'Loading barbers...',
            loadingSlots: 'Loading available slots...',
            noSlots: 'No available slots for the selected day.',
            anyBarber: 'Any barber',
            duration: 'min',
            price: 'Price',
            summary: 'Booking Summary',
            service: 'Service',
            barber: 'Barber',
            date: 'Date',
            time: 'Time',
            loginRequired: 'Please sign in to book an appointment.',
        },
    },
} as const;

type TranslationObj = typeof translations.pl;

function getNestedValue(obj: Record<string, any>, path: string): string {
    const result = path.split('.').reduce<any>((current, key) => current?.[key], obj);
    return typeof result === 'string' ? result : path;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [lang, setLang] = useState<Language>(() => {
        return (localStorage.getItem('language') as Language) || 'pl';
    });

    const toggleLang = () => {
        const newLang = lang === 'pl' ? 'en' : 'pl';
        setLang(newLang);
        localStorage.setItem('language', newLang);
    };

    const t = (path: string): string => {
        return getNestedValue(translations[lang] as Record<string, any>, path);
    };

    return (
        <LanguageContext.Provider value={{ lang, toggleLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = (): LanguageContextType => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within LanguageProvider');
    return context;
};
